### ISSUE TITLE
Installation crashes back-end.

### ISSUE THREAD

**Issue by AngelsDustz** [ingpsp/magento#5]
After adding the files I got from [Magento Marketplace](https://marketplace.magento.com/ingpsp-ing-psp.html) to the root of my Magento 1.9.2.2 installation I am no longer able to go to System -> Configuration.

As it crashes with the following error:
```php
Fatal error: Uncaught Error: Call to a member function isInTestMode() on null in /data/web/public/app/code/community/ING/PSP/Model/Observer.php:137
Stack trace:
#0 /data/web/public/app/code/community/ING/PSP/Model/Observer.php(87): ING_PSP_Model_Observer->getActiveINGProducts()
#1 /data/web/public/app/code/core/Mage/Core/Model/App.php(1357): ING_PSP_Model_Observer->checkPaymentMethodStatus(Object(Varien_Event_Observer))
#2 /data/web/public/app/code/core/Mage/Core/Model/App.php(1336): Mage_Core_Model_App->_callObserverMethod(Object(ING_PSP_Model_Observer), 'checkPaymentMet...', Object(Varien_Event_Observer))
#3 /data/web/public/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('adminhtml_init_...', Array)
#4 /data/web/public/app/code/core/Mage/Adminhtml/Model/Config.php(93): Mage::dispatchEvent('adminhtml_init_...', Array)
#5 /data/web/public/app/code/core/Mage/Adminhtml/Model/Config.php(63): Mage_Adminhtml_Model_Config->_initSectionsAndTabs()
#6 /data/web/public/app/code/core/Mage/Adminhtml/controllers/System/ConfigCo in /data/web/public/app/code/community/ING/PSP/Model/Observer.php on line 137
```

This is caused by `$this->ingAPI` not being set because the api key is not set in the back-end, however it won't let me access my back-end either.

**Comment by geekyjazzy** [comment]
Hi @AngelsDustz , Thanks for this bug. I'll check with our devs and update you.

**Comment by ingpsp** [comment]
@AngelsDustz please use the version from github. The version in Marketplace needs updating. We've submitted the update quite sometime ago, but Magento takes a few months to approve it cause of a huge backlog.
